import { NextRequest, NextResponse } from "next/server";
import { openai } from "@/lib/openai";

// ─── Rich mock per language ───────────────────────────────────────────────────
function getMockResponse(topic: string, grade: string, language: string, misconception: string) {
  const isHindi = language === "Hindi";
  const isHinglish = language === "Hinglish";

  const diagnosisBlock = misconception
    ? isHindi
      ? `## 🔍 गलतफहमी की जड़ (Misconception Diagnosis)

**तुमने सोचा होगा:** "${misconception}"

यह गलती इसलिए हुई क्योंकि अक्सर student यह मान लेते हैं कि... [specific reasoning]. दिमाग में यह rule बैठा होता है जो इस situation में काम नहीं करता।

**असली rule यह है:** पहले समझते हैं कि तुम्हारी सोच कहाँ मुड़ी...

---`
      : isHinglish
      ? `## 🔍 Misconception Diagnosis

**Tumne socha hoga:** "${misconception}"

Yeh galti tab hoti hai jab hum assume kar lete hain ki... [specific rule jo galat hai]. Yeh ek common trap hai — bahut saare students isme phasте हैं।

**Sahi samajh yeh hai:** Chalte hain step by step...

---`
      : `## 🔍 Misconception Diagnosis

**You likely thought:** "${misconception}"

This mistake happens because students often apply a rule that works in simpler cases but breaks down here. The mental model causing this: [specific wrong assumption].

**Here's why that reasoning fails — and the correct thinking:**

---`
    : "";

  const content = `${diagnosisBlock}
## 📖 Explanation: ${topic} (${grade})

${isHindi
  ? `**${topic}** एक बहुत महत्वपूर्ण concept है। आइए इसे real-life example से समझते हैं:\n\n**Concept:** यह तब होता है जब...\n\n**याद रखो:** हर problem को step-by-step solve करो।`
  : isHinglish
  ? `**${topic}** ek important concept hai. Isko ek example se samajhte hain:\n\n**Concept:** Jab bhi yeh situation aaye...\n\n**Tip:** Steps ko skip mat karo — ek ek step karo.`
  : `**${topic}** is a foundational concept in ${grade} curriculum. Let's break it down with a real-world analogy:\n\n**Core Idea:** Think of it like...\n\n**Remember:** Always work step-by-step.`
}

---

## ✏️ Practice Questions (5)

**Q1 (Easy)** ${isHindi ? "आसान सवाल — सीधे formula लगाओ।" : isHinglish ? "Easy wala — seedha formula use karo." : "Apply the basic formula directly."}
> **Answer:** Step 1 → Step 2 → Final answer

**Q2 (Medium)** ${isHindi ? "थोड़ा सोचना होगा।" : isHinglish ? "Thoda socho — direct nahi hai." : "Requires one extra step of thinking."}
> **Answer:** Identify → Setup → Solve

**Q3 (Medium)** ${isHindi ? "Real-life situation वाला सवाल।" : isHinglish ? "Real-life wala question." : "A real-world application problem."}
> **Answer:** Set up equation → Solve → Verify

**Q4 (Hard)** ${isHindi ? "यह tricky है — ध्यान से पढ़ो।" : isHinglish ? "Yeh tricky hai — dhyan se padho." : "Tricky — read carefully before solving."}
> **Answer:** Analyse → Apply concept → Check answer

**Q5 (Challenge)** ${isHindi ? "अगर यह कर लिया तो expert हो!" : isHinglish ? "Agar yeh kar liya toh expert ho!" : "If you solve this, you've mastered the concept!"}
> **Answer:** Multi-step → Concept combination → Final

---

## 📋 Worksheet: ${topic}

| # | Problem | My Working | Answer |
|---|---------|-----------|--------|
| 1 | Basic application | | |
| 2 | Medium level | | |
| 3 | Word problem | | |
| 4 | Advanced | | |
| 5 | Challenge | | |

${isHindi ? "**नाम:** _______________ **दिनांक:** _______________" : isHinglish ? "**Naam:** _______________ **Date:** _______________" : "**Name:** _______________ **Date:** _______________"}

---
*${isHindi ? "VidyaConnect AI Co-Pilot द्वारा बनाया गया" : isHinglish ? "VidyaConnect AI Co-Pilot ne banaya" : "Generated by VidyaConnect AI Co-Pilot"} · GPT-5.6*`;

  return { sections: { explanation: "", practice: "", worksheet: "" }, content, mock: true };
}

// ─── Build the structured prompt ─────────────────────────────────────────────
function buildPrompt(topic: string, grade: string, language: string, misconception: string) {
  const miscSection = misconception
    ? `

IMPORTANT — The student gave this WRONG answer / showed this misconception:
"${misconception}"

START the explanation section with a "Misconception Diagnosis":
1. First say "Tumne/You likely thought: [restate their wrong idea]"
2. Diagnose exactly WHICH wrong mental rule/assumption caused that mistake
3. Explain WHY that rule fails here (not just "wrong" — the mechanism)
4. Then smoothly transition to the correct explanation

Do NOT start with "The correct answer is". Start with the student's wrong thinking.`
    : "";

  const langInstruction =
    language === "Hindi"
      ? "Respond ENTIRELY in Hindi (Devanagari script). Use simple, student-friendly Hindi."
      : language === "Hinglish"
      ? "Respond in Hinglish — mix Hindi words naturally into English sentences. E.g. 'Yeh concept simple hai, bas yeh steps follow karo...'"
      : "Respond in clear, simple English suitable for Indian students.";

  return `You are VidyaConnect AI — an expert ${grade} tutor using GPT-5.6.
${langInstruction}
${miscSection}

Generate teaching material for: "${topic}" for a ${grade} student.

Structure your response with EXACTLY these 3 sections using these exact markdown headers:

## 📖 Explanation
[If misconception provided: start with Misconception Diagnosis block, then teach the concept with real-world analogy]

## ✏️ Practice Questions
[5 questions ranging Easy → Medium → Medium → Hard → Challenge. Each question on its own line. Include the ANSWER after each question]

## 📋 Worksheet
[A printable table with 5 rows: Problem | My Working | Answer. Include name/date line at bottom]

Keep it encouraging, clear, and age-appropriate. Use markdown formatting.`;
}

// ─── Route handler ────────────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  let body: { topic: string; grade: string; language: string; misconception?: string };

  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const { topic, grade, language = "English", misconception = "" } = body;

  if (!topic || !grade) {
    return NextResponse.json({ error: "Topic and grade are required" }, { status: 400 });
  }

  // ── Mock mode (no API key) ──
  if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === "sk-placeholder") {
    await new Promise((r) => setTimeout(r, 2200)); // realistic latency
    return NextResponse.json(getMockResponse(topic, grade, language, misconception));
  }

  // ── Live GPT call ──
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 25000); // 25s timeout

    const response = await openai.chat.completions.create(
      {
        model: "gpt-4o",
        messages: [{ role: "user", content: buildPrompt(topic, grade, language, misconception) }],
        max_tokens: 1200,
        temperature: 0.7,
      },
      { signal: controller.signal }
    );

    clearTimeout(timeout);

    const content = response.choices[0]?.message?.content ?? "";
    if (!content) throw new Error("Empty response from GPT");

    return NextResponse.json({ content, mock: false });
  } catch (err: unknown) {
    console.error("Copilot API error:", err);

    // Timeout or network error → return rich mock, never crash
    const mockData = getMockResponse(topic, grade, language, misconception);
    return NextResponse.json({
      ...mockData,
      mock: true,
      fallback: true,
    });
  }
}
