// ─── Mock data for VidyaConnect AI ───────────────────────────────────────────

export const SUBJECTS = [
  { id: "math",    label: "Mathematics", icon: "calculator",   color: "bg-blue-50 text-blue-700" },
  { id: "science", label: "Science",     icon: "flask",        color: "bg-green-50 text-green-700" },
  { id: "english", label: "English",     icon: "book-open",    color: "bg-purple-50 text-purple-700" },
  { id: "hindi",   label: "Hindi",       icon: "languages",    color: "bg-orange-50 text-orange-700" },
  { id: "physics", label: "Physics",     icon: "atom",         color: "bg-cyan-50 text-cyan-700" },
  { id: "chem",    label: "Chemistry",   icon: "test-tube",    color: "bg-pink-50 text-pink-700" },
  { id: "bio",     label: "Biology",     icon: "leaf",         color: "bg-emerald-50 text-emerald-700" },
  { id: "coding",  label: "Coding",      icon: "code",         color: "bg-violet-50 text-violet-700" },
];

export const TEACHERS = [
  {
    id: "t1",
    name: "Priya Sharma",
    subject: "Mathematics",
    subjectId: "math",
    avatar: "PS",
    avatarBg: "bg-blue-100 text-blue-700",
    rating: 4.9,
    reviews: 128,
    price: 400,
    priceUnit: "hr",
    location: "Lajpat Nagar, Delhi",
    distance: "1.2 km",
    experience: "8 years",
    verified: true,
    online: true,
    bio: "IIT Delhi alumna specialising in Class 9–12 Maths and JEE preparation. 200+ students cracked JEE with my guidance.",
    tags: ["JEE", "CBSE", "Class 9-12"],
    languages: ["Hindi", "English"],
    availability: ["Mon", "Wed", "Fri", "Sat"],
    matchScore: 97,
    sessions: 342,
    grade: "Class 9-12",
    slots: ["9:00 AM", "11:00 AM", "3:00 PM", "5:00 PM", "7:00 PM"],
  },
  {
    id: "t2",
    name: "Arjun Mehta",
    subject: "Science",
    subjectId: "science",
    avatar: "AM",
    avatarBg: "bg-green-100 text-green-700",
    rating: 4.8,
    reviews: 94,
    price: 350,
    priceUnit: "hr",
    location: "Karol Bagh, Delhi",
    distance: "2.4 km",
    experience: "6 years",
    verified: true,
    online: false,
    bio: "AIIMS graduate helping students excel in Biology and Science. Known for making complex concepts crystal clear.",
    tags: ["NEET", "CBSE", "Class 8-12"],
    languages: ["Hindi", "English", "Punjabi"],
    availability: ["Tue", "Thu", "Sat", "Sun"],
    matchScore: 91,
    sessions: 217,
    grade: "Class 8-12",
    slots: ["10:00 AM", "2:00 PM", "4:00 PM", "6:00 PM"],
  },
  {
    id: "t3",
    name: "Kavya Nair",
    subject: "English",
    subjectId: "english",
    avatar: "KN",
    avatarBg: "bg-purple-100 text-purple-700",
    rating: 4.9,
    reviews: 203,
    price: 300,
    priceUnit: "hr",
    location: "Vasant Kunj, Delhi",
    distance: "3.8 km",
    experience: "10 years",
    verified: true,
    online: true,
    bio: "English Literature graduate from Delhi University. Specialise in grammar, creative writing, and spoken English for all ages.",
    tags: ["Grammar", "Writing", "IELTS"],
    languages: ["English", "Malayalam"],
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    matchScore: 88,
    sessions: 456,
    grade: "All grades",
    slots: ["8:00 AM", "10:00 AM", "12:00 PM", "4:00 PM", "6:00 PM"],
  },
  {
    id: "t4",
    name: "Rahul Gupta",
    subject: "Physics",
    subjectId: "physics",
    avatar: "RG",
    avatarBg: "bg-cyan-100 text-cyan-700",
    rating: 4.7,
    reviews: 71,
    price: 450,
    priceUnit: "hr",
    location: "Dwarka, Delhi",
    distance: "5.1 km",
    experience: "5 years",
    verified: true,
    online: true,
    bio: "NIT Trichy graduate. Expert in JEE Physics — mechanics, waves, electromagnetism. Visual teaching method loved by students.",
    tags: ["JEE", "Physics", "Class 11-12"],
    languages: ["Hindi", "English"],
    availability: ["Mon", "Wed", "Fri"],
    matchScore: 85,
    sessions: 189,
    grade: "Class 11-12",
    slots: ["9:00 AM", "1:00 PM", "5:00 PM", "7:00 PM"],
  },
  {
    id: "t5",
    name: "Sunita Verma",
    subject: "Hindi",
    subjectId: "hindi",
    avatar: "SV",
    avatarBg: "bg-orange-100 text-orange-700",
    rating: 4.8,
    reviews: 156,
    price: 250,
    priceUnit: "hr",
    location: "Rohini, Delhi",
    distance: "4.2 km",
    experience: "12 years",
    verified: true,
    online: false,
    bio: "MA Hindi from BHU. Passionate about Hindi literature and language. Makes Hindi grammar fun and easy to understand.",
    tags: ["CBSE", "Grammar", "Literature"],
    languages: ["Hindi"],
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    matchScore: 82,
    sessions: 521,
    grade: "Class 6-12",
    slots: ["7:00 AM", "9:00 AM", "11:00 AM", "3:00 PM"],
  },
  {
    id: "t6",
    name: "Dev Krishnan",
    subject: "Coding",
    subjectId: "coding",
    avatar: "DK",
    avatarBg: "bg-violet-100 text-violet-700",
    rating: 5.0,
    reviews: 42,
    price: 600,
    priceUnit: "hr",
    location: "Noida Sector 62",
    distance: "8.3 km",
    experience: "4 years",
    verified: true,
    online: true,
    bio: "Ex-Flipkart SDE teaching Python, JavaScript, and DSA. 15+ students placed in top tech companies through my mentorship.",
    tags: ["Python", "DSA", "Web Dev"],
    languages: ["English", "Malayalam"],
    availability: ["Tue", "Thu", "Sat", "Sun"],
    matchScore: 79,
    sessions: 97,
    grade: "Class 10+",
    slots: ["10:00 AM", "2:00 PM", "5:00 PM", "8:00 PM"],
  },
];

export const SESSIONS = [
  {
    id: "s1",
    teacherId: "t1",
    teacherName: "Priya Sharma",
    teacherAvatar: "PS",
    avatarBg: "bg-blue-100 text-blue-700",
    subject: "Mathematics",
    date: "Today",
    time: "5:00 PM",
    duration: "60 min",
    status: "upcoming",
    topic: "Quadratic Equations",
  },
  {
    id: "s2",
    teacherId: "t3",
    teacherName: "Kavya Nair",
    teacherAvatar: "KN",
    avatarBg: "bg-purple-100 text-purple-700",
    subject: "English",
    date: "Tomorrow",
    time: "4:00 PM",
    duration: "45 min",
    status: "upcoming",
    topic: "Essay Writing",
  },
  {
    id: "s3",
    teacherId: "t2",
    teacherName: "Arjun Mehta",
    teacherAvatar: "AM",
    avatarBg: "bg-green-100 text-green-700",
    subject: "Science",
    date: "18 Jul",
    time: "10:00 AM",
    duration: "60 min",
    status: "completed",
    topic: "Photosynthesis",
  },
];

export const STATS = [
  { label: "Sessions",    value: 24,  unit: "",    icon: "calendar",   trend: "+3 this week",   color: "bg-blue-50",   iconColor: "text-blue-600" },
  { label: "Hours",       value: 18,  unit: "hrs", icon: "clock",      trend: "+2 this week",   color: "bg-brand-50",  iconColor: "text-brand-600" },
  { label: "Teachers",    value: 4,   unit: "",    icon: "users",      trend: "2 active",       color: "bg-green-50",  iconColor: "text-green-600" },
  { label: "Spent",       value: 7200, unit: "₹", icon: "wallet",      trend: "₹1,200 this month", color: "bg-purple-50", iconColor: "text-purple-600" },
];

export const LEARNING_DNA = [
  { subject: "Mathematics", progress: 72, grade: "B+", color: "bg-blue-500" },
  { subject: "English",     progress: 88, grade: "A",  color: "bg-purple-500" },
  { subject: "Science",     progress: 61, grade: "B",  color: "bg-green-500" },
];

export const QUIZ_QUESTIONS = [
  {
    id: 1,
    question: "What class are you studying in?",
    options: ["Class 6-8", "Class 9-10", "Class 11-12", "Competitive Exam"],
  },
  {
    id: 2,
    question: "Which subject do you need help with most?",
    options: ["Mathematics", "Science", "English", "Hindi / Regional"],
  },
  {
    id: 3,
    question: "How do you learn best?",
    options: ["Visual explanations", "Practice problems", "Reading notes", "Live discussion"],
  },
  {
    id: 4,
    question: "When do you prefer sessions?",
    options: ["Morning (7–12 AM)", "Afternoon (12–4 PM)", "Evening (4–8 PM)", "Night (8–11 PM)"],
  },
  {
    id: 5,
    question: "What's your biggest challenge right now?",
    options: ["Concepts unclear", "Need more practice", "Exam pressure", "Low confidence"],
  },
];
